### ISSUE TITLE
Week 2 assignment

### ISSUE THREAD

**Issue by wibeasley** [wibeasley/regex-class-2015#1]
@andkov, @Maleeha, & @rpoudel, for next week, please complete recipes 2.1 through 2.6 in _both_ regex101.com and R.  Include your work in a folder called `week-2/`, similar to the existing files in `week-1/`.

@rpoudel, if you'd like to catch up, please ask @Maleeha for help.  Both of you would benefit from the repeitition.

**Comment by rpoudel** [comment]
@wibeasley sure.

**Comment by andkov** [comment]
@wibeasley , recipe 2.1 in R turned out more devious than I expected! I can't even load the subject. I feel, like I'm very [close](https://github.com/wibeasley/regex-class-2015/blob/master/week-2/recipes-21-26-andrey.R). Here what I have so far:

```
# capture " by using ' as quotes
cat(s1 <- 'The punctuation characters in the ASCII table are: !"#$%&') 
# caputre ' by using " as quotes
cat(s2 <- "'()*+,-./:;<=>?@[")  
s3 <- "\]^_`{|}~." # produces error
cat(s3 <- "\\]^_`{|}~.") # the first wack is escaped, works
print(s3) # however it stores the first wack
(subject <- paste(s1,s2,s3)) # combines into wrong string
# ... <=>?@[ \\]^_`{|}~.
# instead of
# ... <=>?@[\]^_`{|}~.
```

I bet you would qualify something like

```
s <- paste(s1,s2,cat(s3))
```

as "boneheaded", yet it at least captures the intention in some sort of grammar.  Any hints to direct my thinking?

**Comment by wibeasley** [comment]
Try escaping the backslash:
from

``` r
s3 <- "\]^_`{|}~."
```

to

``` r
s3 <- "\\]^_`{|}~."
```

Does that work?

**Comment by andkov** [comment]
That's my stumbling stone. 

```
> s3 <- "\]^_`{|}~." # produces error
Error: '\]' is an unrecognized escape in character string starting ""\]"
```

I can get it in by wacking the wack

```
s3 <- "\\]^_`{|}~.")
```

but then what do I do with it?

```
subject <- paste(s1,s2,s3)
```

produce incorrect string

```
# ... <=>?@[ \\]^_`{|}~.
# instead of
# ... <=>?@[\]^_`{|}~.
```

**Comment by wibeasley** [comment]
What happens when you use `paste0()` instead of `paste()`?

Also, I'd avoid either paste until you figure things out.  Just slowly build out the regex string within a single pair of quotes.

**Comment by andkov** [comment]
that certainly was boneheaded, but still doesn't solve the problem: it prints two wacks instead of one

```
# ... <=>?@[\\]^_`{|}~.
# instead of
# ... <=>?@[\]^_`{|}~.
```

And I can't remove the first wack, because it doesn't count as a character

```
> s3
[1] "\\]^_`{|}~."
> nchar(s3)
[1] 10
```

**Comment by andkov** [comment]
I guess my question can be simplified.

```
a <- "\"
```

is wrong. How do I do what it tries to? How do I create a character vector in R which content is a literal character `\`

**Comment by wibeasley** [comment]
Oh, ok.  **If you want to match a literal `\` in the regex**, you'll need four whacks in the string defined in R (ie `\\\\`).

Working forwards, the four whacks `\\\\` will condense down to two when it gets to the regex `\\`.  You need two within the regex pattern, because you need the first one to "escape" the second one.

Or said another way: Working backwards, you need two whacks in the regex pattern `\\` (because you need the first one to "escape" the second one).  In order to get two whacks through to the regex pattern, you need to escape _both_ of them as you define the string in R.

**Comment by andkov** [comment]
That's preemptively useful, thanks! However, I don't think this addresses my problem. Perhaps I'm understanding the task incorrectly? I've already completed recipe 2.1 in regex101.com view. Now I'm moving to R. The task is as follows:

A. Create a character vector `subject` containing the following string

> The punctuation characters in the ASCII table are: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~.

B. Create such `regex` pattern and use `grep()` function to return matching string from the object `subject`

```
regex <- "..."
grep(pattern=regex, subject, value=T, perl=T))
```

I'm not stuck on B, but on A. Creating a character vector in R that contains precisely the string

> The punctuation characters in the ASCII table are: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~.

I've worked around importing symbols " and ' ,  but I can't import a single \ 
It either produces an error

```
> a <- "[\]
Error: '\]' is an unrecognized escape in character string starting ""[\]"
```

or inserts and extra \ into the string when I escape the wack

```
> a <- "[\\]"
> a
[1] "[\\]"
```

I presume we need `subject` to be exactly

> The punctuation characters in the ASCII table are: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~.

and **NOT**

> The punctuation characters in the ASCII table are: !"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~.

**Comment by wibeasley** [comment]
But I think this is correct.  It's supposed to be doubled when you print it out.  Why do you think it's wrong?  Sorry if I'm misunderstanding.
![image](https://cloud.githubusercontent.com/assets/1372890/11596818/222067b6-9a7d-11e5-80da-e7066816c070.png)

**Comment by andkov** [comment]
Ah, yes, I think I can trace my misunderstanding. I was assuming that it must be a single \ when printed in R because that's the precise literal value as I saw typed up in the book.  Then I presume the following script assembles the correct subject for recipe 2.1

```
> # capture " by using ' as quotes
> cat(s1 <- 'The punctuation characters in the ASCII table are: !"#$%&')
The punctuation characters in the ASCII table are: !"#$%&
> # caputre ' by using " as quotes
> cat(s2 <- "'()*+,-./:;<=>?@[")
'()*+,-./:;<=>?@[
> s3 <- "\]^_`{|}~." # produces error
Error: '\]' is an unrecognized escape in character string starting ""\]"
> cat(s3 <- "\\]^_`{|}~.") # the first wack is escaped, works
\]^_`{|}~.
> print(s3) # however it stores the first wack
[1] "\\]^_`{|}~."
> (subject <- paste0(s1,s2,s3)) # combines into wrong string
[1] "The punctuation characters in the ASCII table are: !\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~."
> cat(subject)
The punctuation characters in the ASCII table are: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~.
```

**Comment by andkov** [comment]
Ah, yes. I was assuming that it must be a single \ when printed in R because that's the precise literal value as I saw typed up in the book.

**Comment by wibeasley** [comment]
Cool.  If you get stuck again on this one, either (a) ignore the backslash or (b) move on to recipe 2.2.

**Comment by Maleeha** [comment]
[Regex Homework.docx](https://github.com/wibeasley/regex-class-2015/files/58467/Regex.Homework.docx)
Starting with 2.1
- [x] Muthen.&.Muthen. _this is what we do when we need to find a certain statement in a text_
- [x] We can escape the meta-characters by a backslash '\'
- [x] ]-} only become meta-characters, only if they are preceded by their un-escaped counterparts
- [x] Escaping a non-alphanumeric character can give it a special meaning or result in a syntax error
- [x] \Q and \E suppress the meaning of meta-characters
- [x] All regular expressions are case-sensitive
- [x] Muthen.&(?i).muthen _case insensitivity_. (?I) is a mode-modifier.
- [x] Muthen.&(-?i).muthen \* turns off case insensitivity*. Is also a mode modifier.

**2.1 gives me this match information from regex101**

_No match groups were extracted._

_This means that your pattern matches but there were no (capturing (groups)) in it that matched anything in the subject string._

**Comment by Maleeha** [comment]
Starting with 2.2
- [x] Some control characters have hexa-decimal codes. _e.g. bell, escape, form feed, line feed, carriage return, horizontal tab, vertical tab_
- [x] Also escape sequences. Is that backslash \?
- [x] \cA through \cZ is another way of representing 26 control characters in the ASCII table. **Small c with a capital A through Z**
- [ ] A lowercase \x followed by two hexadecimal digits matches a single character in ASCII table. **I don't get this.**
- [ ] What's a Unicode? :octocat:

**Comment by Maleeha** [comment]
Starting with 2.3
- [x] Attend to all common misspellings
- [x] Create a regular expression to match a hexa-decimal character
- [x] Create a regular expression to match a non hexa-decimal character.
- [x] Any notation with a square bracket is a character class.
- [x] Meta-character inside a character class having special meanings are**\,^,- and ]**
- [x] The remaining 4 characters get their special meaning when placed within a certain way in a character class
- [x] Backslash escapes the character that follows it. The use of backslash is recommended.
- [x] These 4 meta-characters can be literal characters if placed within certain positions in a character class [ ] [^-]
- [x] All other meta-characters are literal within the character class. [$()*+.?{]. Only have special meanings outside the character class. 
- [x] Alphanumeric characters cannot be escaped with a backslash. \
- [x] Certain Alphanumeric characters can be used with a backslash within a character class (\n \r) for line feed and a carriage return respectively.
-  (^) negates a character class if you place it immediately after the opening bracket.
-  (-) creates a range when placed between two characters.
- [x] Short-hand character classes **\d, \D, \w, \W, \s, \S** Can be used both inside and outside character classes
- [x] e.g. \D is equal to [^\d]
- [ ] What's a word character (letters, digits, _)
- [ ] \w is identical to [a-zA-Z0-9_]
- [ ] \s matches any white-space character (spaces, tabs and line breaks) or any character defined as a white space character by the Unicode standards
- [x] Mode Modifier for case-insensitivity can be used with a character class. (?i)
- [x] [class-[subtract]] is complex **Base class and a nested class**
- [ ] Unicode categories, blocks and scripts.
- [ ] ‹[a-f[A-F][0-9]] **Class Union**
- [ ] [\w&&[a-fA-F0-9\s]] *\* Class Intersection**
- [ ] ‹[a-zA-Z0-9&&[^g-zG-Z]] **Class Subtraction**
  *\* SO many questions on 2.3**
  [Recipe 2.3.docx](https://github.com/wibeasley/regex-class-2015/files/58672/Recipe.2.3.docx)

**Comment by Maleeha** [comment]
Starting 2.4
- [x] Dot matches line break. 
- [x] [\s\S], [\d\D], [\w\W] have the same effect
- [ ] Could you please explain [/.-] in ‹\d\d[/.-]\d\d[/.-]\d\d› **Why do we need to escape a hypen here?
- [ ] Use the dot only when you really want to allow any character. Use a character class or
  negated character class in any other situation. **What does this mean?**
- [ ] In case if a dot does not match a line break, then we can use a mode-modifier (?m)'.'
  (?s) matches line break

**Comment by wibeasley** [comment]
Read this about escape characters: http://www.explainxkcd.com/wiki/index.php/234

The comic's explanation at the bottom of the page will actually help you understand this class.

**Comment by Maleeha** [comment]
Thank you @wibeasley ! Thanks @rpoudel  for the references last night!
Here, I found examples of Non-Alphanumeric Tokens. I don't know how much of this actually applies because we already know that  '+, ^, *, {, [ are also meta-characters, giving regular expressions their special meaning. So don't escape non-alphanumeric if they are not meta-characters because then that will result in syntax errors/special meanings.
[Non-Alphanumeric Tokens.docx](https://github.com/wibeasley/regex-class-2015/files/59819/Non-Alphanumeric.Tokens.docx)
