### ISSUE TITLE
Exercise - Regex

### ISSUE THREAD

**Issue by andkov** [wibeasley/regex-class-2015#10]
@wibeasley, FYI

Given the subject
```
001 Fernie
021 Armstrong - Spallumcheen
023 Central Okanagan
045 West Vancouver-Bowen Island
162 Vancouver - Downtown Eastside
202 South Surrey/White Rock
BC
Unknown HA
```
compose a regex expression to capture the number (optional group 1) and descriptive label (mandatory group 2).

Here's a starter for regex101.com
```
(\d+) (\w+)
```

**Comment by wibeasley** [comment]
pattern (before escaping the backslashes for R): `^(\d{2,3})?\s*(.+)$`
substitution: `[\1]-{\2}`

![image](https://user-images.githubusercontent.com/1372890/30749347-b659f378-9f78-11e7-9a83-64c8dee83093.png)
