### ISSUE TITLE
Week 3 assignment

### ISSUE THREAD

**Issue by wibeasley** [wibeasley/regex-class-2015#2]
@andkov @Maleeha @rpoudel 

use `gsub()` to extract the
- Maximum number of iterations for H1
- Maximum number of iterations
- Derivative

```
Estimator                                                      MLF
Information matrix                                        OBSERVED
Maximum number of iterations                                   100
Convergence criterion                                    0.100D-05
Maximum number of EM iterations                               1000
Convergence criteria for the EM algorithm
  Loglikelihood change                                   0.100D-02
  Relative loglikelihood change                          0.100D-05
  Derivative                                             0.100D-03
Minimum variance                                         0.100D-03
Maximum number of steepest descent iterations                   20
Maximum number of iterations for H1                           2000
Convergence criterion for H1                             0.100D-04
Optimization algorithm                                         EMA
```

from https://github.com/IALSA/IALSA-2015-Portland/blob/master/studies/eas/physical/b1_male_aehplus_grip_gait.out

**Comment by wibeasley** [comment]
Here's a start.

_Code_:

``` r
subject <- 
"Estimator                                                      MLF
Information matrix                                        OBSERVED
Maximum number of iterations                                   100
Convergence criterion                                    0.100D-05
Maximum number of EM iterations                               1000
Convergence criteria for the EM algorithm
  Loglikelihood change                                   0.100D-02
  Relative loglikelihood change                          0.100D-05
  Derivative                                             0.100D-03
Minimum variance                                         0.100D-03
Maximum number of steepest descent iterations                   20
Maximum number of iterations for H1                           2000
Convergence criterion for H1                             0.100D-04
Optimization algorithm                                         EMA"

regex_estimator <- "(?s).*?Estimator\\s+(\\w+).*"
estimator <- gsub(regex_estimator, "\\1", subject, perl=T)

print(estimator)
```

_Output_:

```
[1] "MLF"
```

Note: the `(?s)` is toggling an option.  It's not a capturing group.  As it says on page 40 of our book:

> ‹(?s)› is the mode modifier for “dot matches line breaks” mode in .NET, Java, XRegExp,
> PCRE, Perl, and Python.

**Comment by rpoudel** [comment]
Just for the reference,

Regular Expression Syntax:
Syntax  Description
\d Digit, 0,1,2 ... 9
\D Not Digit
\s Space
\S Not Space
\w Word
\W Not Word
\t Tab
\n New line
^   Beginning of the string
$   End of the string
\   Escape special characters, e.g. \ is "\", + is "+"
|   Alternation match. e.g. /(e|d)n/ matches "en" and "dn"
• Any character, except \n or line terminator
[ab]    a or b
[^ab]   Any character except a and b
[0-9]   All Digit
[A-Z]   All uppercase A to Z letters
[a-z]   All lowercase a to z letters
[A-z]   All Uppercase and lowercase a to z letters
i+  i at least one time
i\*  i zero or more times
i?  i zero or 1 time
i{n}    i occurs n times in sequence
i{n1,n2}    i occurs n1 - n2 times in sequence
i{n1,n2}?   non greedy match, see above example
i{n,}   i occures >= n times
[:alnum:]   Alphanumeric characters: [:alpha:] and [:digit:]
[:alpha:]   Alphabetic characters: [:lower:] and [:upper:]
[:blank:]   Blank characters: e.g. space, tab
[:cntrl:]   Control characters
[:digit:]   Digits: 0 1 2 3 4 5 6 7 8 9
[:graph:]   Graphical characters: [:alnum:] and [:punct:]
[:lower:]   Lower-case letters in the current locale
[:print:]   Printable characters: [:alnum:], [:punct:] and space
[:punct:]   Punctuation character: ! " # $ % & ' ( ) \* + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
[:space:]   Space characters: tab, newline, vertical tab, form feed, carriage return, space
[:upper:]   Upper-case letters in the current locale
[:xdigit:]  Hexadecimal digits: 0 1 2 3 4 5 6 7 8 9 A B C D E F a b c d e f

**Comment by wibeasley** [comment]
@rpoudel, ignore everything below `[:alnum:]`.  That's the syntax for ["POSIX" regexes](https://www.stat.auckland.ac.nz/~paul/ItDT/HTML/node84.html#SECTION001521000000000000000) --not "Perl" regexes.  For a few reasons, we're sticking with Perl-ish regexes.

---

I think I said it, but didn't write this: everyone should keep working on the remainder of the Week 2 assignments after you're done with this week's.

**Comment by rpoudel** [comment]
Sure @wibeasley

**Comment by wibeasley** [comment]
How are people coming on this?  Any snags?

**Comment by andkov** [comment]
I'm still wrapping up and playing with examples  from last session. Learning a lot, but perhaps not in needed structure. I'll keep it more to the lectures.

**Comment by Maleeha** [comment]
Same here. Want to work on the previous session first, a lot more before I move onto the next.

**Comment by wibeasley** [comment]
I suggest trying this week 3 a little bit, before returning to week 2.  I think this will give you a broader perspective of the uses & advantages of regexes.

Modify the `regex_estimator <- "(?s).*?Estimator\\s+(\\w+).*"` part ot meet those three goals.  

If you still haven't gotten anywhere after 10 or 15 minutes, return to Week 2.

**Comment by Maleeha** [comment]
@wibeasley, on it!

**Comment by Maleeha** [comment]
Just worked a bit on 3.1. Its pretty basic but its working.

Regex3.1 (**at line 28-33** and labeled as 'Code 3.1'):
https://github.com/wibeasley/regex-class-2015/blob/3b809040dc79c4e486333d397a793f1aee4b2255/week-2/Week%203%20Regex%20Assignment-Maleeha.R

**Regex Code 3.1**

```
(?s).*Maximum number of iterations for H1(?s).*?(\d+).*
```

Regex3.2 (**at line 35-40** and labeled as 'Code 3.2'):
https://github.com/wibeasley/regex-class-2015/blob/3b809040dc79c4e486333d397a793f1aee4b2255/week-2/Week%203%20Regex%20Assignment-Maleeha.R

**Regex Code 3.2**

```
(?s).*Maximum number of EM iterations(?s).*?(\d+).*
```

Regex3.3(**at line 42-47** and labeled as 'Code 3.3):
https://github.com/wibeasley/regex-class-2015/blob/3b809040dc79c4e486333d397a793f1aee4b2255/week-2/Week%203%20Regex%20Assignment-Maleeha.R

**Regex Code 3.3**

```
(?s).*Derivative(?s).*?(\d.\d*\w.\d+).*
```

[Regex Assignment 3.1.docx](https://github.com/wibeasley/regex-class-2015/files/63206/Regex.Assignment.3.1.docx)

@wibeasley How does this look? :metal:

**Comment by wibeasley** [comment]
@Maleeha, put the regex pattern (and any relevant options or substitutions) as text into this issue.  Alternatively, link to your code in the repo that has the R regex.

**Comment by Maleeha** [comment]
@wibeasley, sorry I have never done text before. I will just try it this once and then more. Can you please teach me how to work the alternative? Linking and all!

**Comment by wibeasley** [comment]
> I have never done text before. I will just try it this once and then more

See item 9 of Can you please teach me how to work the alternative?

> Can you please teach me how to work the alternative?

See items 3 & 4 of https://github.com/OuhscBbmc/RedcapExamplesAndPatterns/issues/3

**Comment by rpoudel** [comment]
https://github.com/wibeasley/regex-class-2015.git

**Comment by Maleeha** [comment]
@wibeasley done!

**Comment by rpoudel** [comment]
@wibeasley I have put code for assignment 2 and 3 with my name. Sorry before I just wrote them in a comment of issues you created. I have some more to do and will do it soon.

**Comment by Maleeha** [comment]
@wibeasley I need a reminder of what does `"\\1"` do in the following gsub

```
derivative<- gsub(regex_derivative, "\\1", subject, perl=T)
```

**Comment by rpoudel** [comment]
@wibeasley and @Maleeha I will try here:
\1returns the first part of the regular expression

**Comment by wibeasley** [comment]
> \1 returns the first part of the regular expression

correct, @rpoudel.  And to be more specific, it "returns the first _capturing group_ of the regular expression"

**Comment by Maleeha** [comment]
:+1: 
Thank you both!

**Comment by rpoudel** [comment]
@wibeasley for tomorrow class, which chapter are we going through?

**Comment by wibeasley** [comment]
I haven't thought about it much.  Maybe we'll spend the first 30 minutes on project management stuff, such as settings timelines and milestones.  You're welcome to join us if you want to learn the system more.  We developed it witht he hope it can apply to almost any distributed/remote data analysis project.  Once that is settled, we'll move to regexes.  We'll feel out where people are, and what would be most productive.

**Comment by rpoudel** [comment]
Thanks and I will join to learn the system.

**Comment by andkov** [comment]
Sorry, I'll still be on vacation. Coming back Saturday. All the newly absorbed vitamin D will pay off, I promise.
