### ISSUE TITLE
Quick applied question

### ISSUE THREAD

**Issue by andkov** [wibeasley/regex-class-2015#6]
@wibeasley , if you have a minute, please give  a hint help me along. 

WIth the subject

```
intage2000     
intage2005     
intage2009     
measure_a_2000 
measure_a_2005
measure_a_2009 
measure_b_2000 
measure_b_2005 
measure_b_2009
```

I would like to parse the last four digits to store as the year indicator. My verbal rule is as follows: select any string that ends in exactly four text characters belong to the set {0-9} that are preceded by any number word characters.

`(^(\w+)([0-9])`, but that gets only the last character in the second capturing group. How do I extend it to 4? I Could you please give me a push in the right direction?

**Comment by wibeasley** [comment]
Your main question: use `[0-9]{4}` instead of `[0-9]`.

Other tips:
1. use the shortcut for digits `\\d{4}` instead of `[0-9]{4}`
2. watch out for that initial open parenthesis (before the carat) that apparently is never closed.

**Comment by wibeasley** [comment]
Here's a complete example with a little extra sauce.  I forgot to mention how to avoid the optional underscore between the measure and the year.  You'll need to use a lazy quantifier

``` r
a <- c(
  "intage2000",
  "intage2005",
  "intage2009",
  "measure_a_2000",
  "measure_a_2005",
  "measure_a_2009",
  "measure_b_2000",
  "measure_b_2005",
  "measure_b_2009"
)

regex <- "^(\\w+?)_?(\\d{4})$"
(measure <- gsub(regex, "\\1", a))
(year <- gsub(regex, "\\2", a))
```

```
> (measure <- gsub(regex, "\\1", a))
[1] "intage"    "intage"    "intage"    "measure_a" "measure_a"
[6] "measure_a" "measure_b" "measure_b" "measure_b"

> (year <- gsub(regex, "\\2", a))
[1] "2000" "2005" "2009" "2000" "2005" "2009" "2000" "2005" "2009"
```

**Comment by andkov** [comment]
This is very illuminating,  thank you!

**Comment by andkov** [comment]
Given the frequency this problem occurs (dissecting variable names that include temporal markers after elongating the dataset with respect to time) , I am tempted to start an exposition of examples. This seems like the perfect setting to realize the importance of regular expressions.

**Comment by wibeasley** [comment]
@andkov In this instance, consider saying "_widening_ the dataset with respect to time" instead of "elongating the dataset with respect to time".  Is this similar to what we were planning with the `zzz_t1` naming scheme in the stencil?

@Maleeha, were you going make an example data set (in the stencil), or am I making that up?  I don't see an [issue](https://github.com/IALSA/ialsa-2015-portland-stencil/issues) for it.

**Comment by andkov** [comment]
@wibeasley , I guess we have different points of reference. We have a wide dataset with respect to time (variable in every time point gets a separate column) so we make it long and then bring it back to wide. The resultant wide, however, has been elongated with respect to time, while staying wide with respect to variable name (variable for all time points has a single column).  The resultant wide data set has _fewer_ columns than the initial wide. It seems that you are referring as _widening_ only  to the last step of the process (casting from d_long into wide).

**Comment by wibeasley** [comment]
I'm not following.  You're probably right that you're using the right terms in this case.  Call if you think it's important for me to understand.

**Comment by andkov** [comment]
i do want to talk this through the next time we talk. Because this process is ubiquitous in data grooming, so I want to make sure we are speaking the same language. I was just making stuff up for lack of the better wording, so i hope to hear how you name them.

**Comment by Maleeha** [comment]
@wibeasley, i just vaguely remember the instructions on an example data set. What was the example data set going to be about? I am 94% sure, i never created an issue for it. I will go ahead create one after you guide me more on this.

**Comment by wibeasley** [comment]
Convert EAS (or something like that) to the exact wide format that we want them to mimic.
