### ISSUE TITLE
Practice problem - model estimates 

### ISSUE THREAD

**Issue by andkov** [wibeasley/regex-class-2015#8]
@wibeasley @Maleeha 

I ran into a practical problem that I thought would be a nice exercise for this forum. If you have a free minute, please consider the following regex task:

I have a column of data that was assembled in Excel that lists the parameters of a statistical model: estimate and the confidence intervals. i would like to split them up into three columns with corresponding elements using regexes. Here's what I have so far.

```r
subject <- c(
  "0.96 (0.88, 1.04)",
  "1.45(0.92,2.29)",
  "0.61 (0.075, 4.86)",
"1"
)
regex_estimator <- "^(\\d.\\d+.*?)\((\\d.\\d+,).*?(\\d.\\d+)"
estimator <- gsub(regex_estimator, "\\1", subject, perl=T)
print(estimator)
```

Which, obviously, does not work. Do you see what I am doing wrong?

However, when I treat this subject
```
0.96 (0.88, 1.04)
1.45(0.92,2.29)
0.61 (0.075, 4.86)
```
at the regex101.com  with this regex
```
^(\d.\d+.*?)\((\d.\d+,).*?(\d.\d+)
```
it splits the subject into proper groups. So I think i'm translating the regex into R flavor incorrectly.  Any suggestions?

**Comment by wibeasley** [comment]
In this case, drop the lazy quantifiers of the all-matching dot.  Instead, capture them with an optional white-space token (ie, `\s`).  There were sometimes spaces (and sometimes no spaces) between the numbers , commas, and parentheses.

Also, I generalized it a tad to it could handle negative coefficients (see the two `-?`) and values larger the 9.999.

```r
subject <- c(
  "0.96 (0.88, 1.04)",
  "1.45(0.92,2.29)",
  "0.61 (0.075, 4.86)",
  "-1.45(0.92,2.29)",
  "10.61 (0.075, 4.86)",
  "1"
)
regex_estimator <- "^(-?\\d+.\\d+)\\s*\\((\\d+.\\d+),\\s*(-?\\d+.\\d+)\\)$"
estimator <- gsub(regex_estimator, "\\1--\\2--\\3", subject, perl=T)
```

**Comment by andkov** [comment]
@wibeasley , thank you. It's the optional spaces that were tripping me up.
